from pyback.rest.errors.base_error import BaseError


class InternalError(BaseError):
    pass
